# Generated by Django 5.2.2 on 2025-06-07 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Название города на английском языке",
                        max_length=100,
                        verbose_name="Город",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Дата в формате YYYY-MM-DD",
                        verbose_name="Дата прогноза",
                    ),
                ),
                (
                    "min_temperature",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Минимальная температура в градусах Цельсия",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(-100.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Минимальная температура",
                    ),
                ),
                (
                    "max_temperature",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Максимальная температура в градусах Цельсия",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(-100.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Максимальная температура",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Пользовательский прогноз",
                "verbose_name_plural": "Пользовательские прогнозы",
                "ordering": ["-date", "city"],
                "indexes": [
                    models.Index(
                        fields=["city", "date"], name="weather_cus_city_133649_idx"
                    ),
                    models.Index(fields=["date"], name="weather_cus_date_414831_idx"),
                ],
                "unique_together": {("city", "date")},
            },
        ),
    ]
