[project]
name = "weatherapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.2",
    "djangorestframework>=3.16.0",
    "ruff>=0.11.13",
]
